
image: docker:20.10.16

services:
  - docker:20.10.16-dind

before_script:
  - docker info

stages:         
  - build-app
  - test-app

build_job:
  stage: build-app
  script:
    - echo "Building Spring Boot app..."
   # - apk --no-cache add openjdk17 maven
    - mvn package

test_job:
  stage: test-app
  script:  
    - echo "Running tests..."
    - apk --no-cache add openjdk17 maven
    - mvn test



