version: "3.8"

services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=measurements
    ports:
      - '5432:5432'
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: back_app
    ports:
      - '8082:8082'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/measurements
      - SPRING_DATASOURCE_USERNAME=main
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_SHOW-SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - db
    restart: always




